<?php

namespace Tests\App\Http\Controllers;

use App\Book;
use TestCase;
use Laravel\Lumen\Testing\DatabaseMigrations;
use Carbon\Carbon;

class BooksControllerTest extends TestCase
{
    use DatabaseMigrations;

    // servono per moccare Carbon e non avere errori nel Mockery per le created_at e updated_at perché sono dinamiche
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Carbon::setTestNow(Carbon::now('UTC'));
    }
    // servono per moccare Carbon e non avere errori nel Mockery per le created_at e updated_at perché sono dinamiche
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        Carbon::setTestNow();
    }


    public function testStoreAnewBookIntoTheDatabase()
    {
        $this->markTestSkipped();
        $this->post('/books', [
           'title' => 'The Invisible Man',
           'description' => 'An invisible man is trapped in the terror of his own
creation',
           'author' => 'H. G. Wells'
        ]);

        $body = json_decode($this->response->getContent(), true);

        $this->assertArrayHasKey('data', $body);

        $data = $body['data'];

        $this->assertEquals('The Invisible Man', $data['title']);
        $this->assertEquals('An invisible man is trapped in the terror of his own
creation', $data['description']);
        $this->assertEquals('H. G. Wells', $data['author']);
        $this->assertTrue($data['id'] > 0);
        $this->seeInDatabase('books', ['title' => 'The Invisible Man']);
    }


    /** @test */
    public function testShowReturnAValidBook()
    {
        $this->markTestSkipped();
        $book = factory('App\Book')->create();

        $this->get("/books/{$book->id}")
            ->seeStatusCode(200)
            ->seeJson([
                'id' => $book->id,
                'title' => $book->title,
                'description' => $book->description,
                'author' => $book->author
           ]);

        $data = json_decode($this->response->getContent(), true);

        $this->assertArrayHasKey('created_at', $data);
        $this->assertArrayHasKey('updated_at', $data);
    }

    /** @test */
    public function testShowFailBookNotExists()
    {
        $this->get('/books/99999', ['Accept' => 'application/json'])
            ->seeStatusCode(404)
            ->seeJson([
                    'message' => 'Not Found',
                    'status' => 404
            ]);
    }

    /** @test */
    public function testStoreANewBookIntoTheDatabaseRevisitedWithCarbonAndFractalResponses()
    {
        $this->post('/books', [
            'title' => 'The invisible Man',
            'description' => 'An invisible man is trapped in the terror of his own creation',
            'author' => 'H. G. Wells'
        ]);

        $body = json_decode($this->response->getContent(), true);
        $this->assertArrayHasKey('data', $body);

        $data = $body['data'];
        $this->assertEquals('The invisible Man', $data['title']);
        $this->assertEquals('An invisible man is trapped in the terror of his own creation', $data['description']);
        $this->assertEquals('H. G. Wells', $data['author']);
        $this->assertTrue($data['id'] > 0, 'Expected positive integer, but did not see once');
        $this->assertArrayHasKey('created_at', $data);
        $this->assertEquals(Carbon::now()->toIso8601String(), $data['created_at']);
        $this->assertArrayHasKey('updated_at', $data);
        $this->assertEquals(Carbon::now()->toIso8601String(), $data['updated_at']);

        $this->seeInDatabase('books', ['title' => 'The Invisible Man']);
    }

    /** @test */
    public function testStoreANewBook()
    {
        $this->post('/books', [
            'title' => 'The invisible Man',
            'description' => 'An invisible man is trapped in the terror of his own creation',
            'author' => 'H. G. Wells'
        ]);

        $this->seeJsonStructure([
            'data' => [
                'title',
                'description',
                'author',
                'updated_at',
                'created_at',
                'id',
            ]
        ]);

        $this->seeInDatabase('books', ['title' => 'The invisible Man']);
    }

    /** @test */
    public function testStore201AndLocationHeaderSuccess()
    {
        $this->post('/books', [
            'title' => 'Lorem ipsum',
            'description' => 'Lorem ipsum dolor sin amet',
            'author' => 'Lorem Ipsum'
        ]);

        $this->seeStatusCode(201)
            ->seeHeaderWithRegExp('Location', '#/books/[\d]+$#');
    }

    /** @test */
    public function testUpdateShouldOnlyChangeFillableFields()
    {
        $this->markTestSkipped('Because update a real book');

        $this->notSeeInDatabase('books',[
           'title' => 'The War of the Worlds'
        ]);

        $this->put('/books/1', [
           'id' => 5,
           'title' => 'The War of the Worlds',
           'description' => 'The book is way better than the movie',
           'author' => 'Wells, H.G.'
        ]);

        $this->seeStatusCode(200)->seeJson([
            'id' => 1,
            'title' => 'The War of the Worlds',
            'description' => 'The book is way better than the movie',
            'author' => 'Wells, H.G.'
        ])->seeInDatabase('books', [
            'title' => 'The War of the Worlds'
        ]);
    }

    /** @test */
    public function testUpdateShouldOnlyChangeFillableFieldsWithAdditionalChecksForFractalResponses()
    {
        $book = factory('App\Book')->create([
            'title' =>  'The War of the Worlds',
            'description' => 'A science fiction masterpiece about Martians invaders',
            'author' => 'Wells, H.G.'
        ]);

        $this->notSeeInDatabase('books', [
            'title' =>  'The War of the Worlds',
            'description' => 'The book is way better than the movie',
            'author' => 'Wells, H.G.'
        ]);

        $this->put("/books/{$book->id}", [
            'id' => 5,
            'title' => 'Book updated',
            'description' => 'The book is way better than the movie',
            'author' => 'Roberto Gianotto'
        ]);

        $this->seeStatusCode(200)
            ->seeJson([
                'id' => 1,
                'title' => 'Book updated',
                'description' =>  'The book is way better than the movie',
                'author' => 'Roberto Gianotto'
            ])
            ->seeInDatabase('books', [
                'title' => 'Book updated'
            ]);

        $body = json_decode($this->response->getContent(), true);
        $this->assertArrayHasKey('data', $body);
        $data = $body['data'];
        $this->assertArrayHasKey('created_at', $data);
        $this->assertEquals(Carbon::now()->toIso8601String(), $data['created_at']);
        $this->assertArrayHasKey('updated_at', $data);
        $this->assertEquals(Carbon::now()->toIso8601String(), $data['updated_at']);
    }

    /** #@test */
    public function testRefactoringUpdateShouldOnlyChangeFillableFields()
    {
        $book = factory('App\Book')->create([
           'title' =>  'The War of the Worlds',
           'description' => 'The book is way better than the movie',
           'author' => 'Wells, H.G.'
        ]);

        $this->seeInDatabase('books', [
           'title' =>  'The War of the Worlds',
            'description' => 'The book is way better than the movie',
            'author' => 'Wells, H.G.'
        ]);

        $this->put("/books/{$book->id}", [
           'id' => 5,
           'title' => 'Book updated',
           'description' => 'The book is way better than the movie',
           'author' => 'Roberto Gianotto'
        ]);

        $this->seeStatusCode(200)
            ->seeJson([
               'id' => 1,
               'title' => 'Book updated',
               'description' =>  'The book is way better than the movie',
               'author' => 'Roberto Gianotto'
            ])
           ->seeInDatabase('books', [
              'title' => 'Book updated'
           ]);
    }

    /** #@test */
    public function testRefactorRemoveAValidBook()
    {
        $book = factory('App\Book')->create();

        $this->delete("/books/{$book->id}")->seeStatusCode(204)->isEmpty();

        $this->notSeeInDatabase('books', ['id' => $book->id]);
    }

    /** @test */
    public function testShouldFailWithAnInvalidId()
    {
        $this->put('/books/99999999999999')
            ->seeStatusCode(404)
            ->seeJsonEquals([
              'error' => [
                  'message' => 'Book not found'
              ]
            ]);
    }

    /** @test */
    public function testUpdateShouldNoMatchAnInvalidRoute()
    {
        $this->put('/books/this-is-invalid')
            ->seeStatusCode(404);
    }

    /** #@test */
    public function testRemoveAValidBook()
    {
        $this->markTestSkipped();
        $this->delete('/books/13')
            ->seeStatusCode(204)
            ->isEmpty();

        $this->notSeeInDatabase('books', ['id' => 13]);
    }

    /** #@test */
    public function testRemoveReturnA404WithAnInvalidId()
    {
        $this->delete('/books/999999999999')
            ->seeStatusCode(404)
            ->seeJsonEquals([
               'error' => [
                   'message' => 'Book not found'
               ]
            ]);
    }

    /** #@test */
    public function testRemoveShouldNotMathAValidRoute()
    {
        $this->delete('/books/this-is-invalid')
            ->seeStatusCode(404);
    }

    /** #@test */
    public function indexShouldReturnACollectionOfRecords()
    {
        $books = factory('App\Book', 2)->create();

        $this->get('/books');

        // nuova modifica con Fractal
//        $expected = [
//          'data' => $books->toArray()
//        ];



//        $this->seeJsonEquals($expected);
        // fine nuova versione con Fractal

//        foreach ($books as $book){
//            $this->seeJson([
//               'title' => $book->title
//            ]);
//        }


        // refactoring per risposta con FractalResponse

        $content = json_decode($this->response->getContent(), true);

        $this->assertArrayHasKey('data', $content);

        foreach($books as $book){
            $this->seeJson([
               'id' => $book->id,
               'title' => $book->title,
               'description' => $book->description,
               'author' => $book->author,
               'created_at' => $book->created_at->toIso8601String(),
               'updated_at' => $book->updated_at->toIso8601String(),
            ]);
        }

    }

    /** @test */
    public function testShouldReturnAValidBookNewVersion()
    {
        $book = factory('App\Book')->create();

//        $expected = [
//            'data' => $book->toArray()
//        ];
//
//        $this->get("/books/{$book->id}")->seeStatusCode(200)->seeJsonEquals($expected);

        // refactoring per FractalResponse

        $this->get("books/{$book->id}")->seeStatusCode(200);

        $content = json_decode($this->response->getContent(), true);

        $this->assertArrayHasKey('data', $content);

        $data = $content['data'];

        $this->assertEquals($book->id, $data['id']);
        $this->assertEquals($book->title, $data['title']);
        $this->assertEquals($book->description, $data['description']);
        $this->assertEquals($book->author, $data['author']);
        $this->assertEquals($book->created_at->toIso8601String(), $data['created_at']);
        $this->assertEquals($book->updated_at->toIso8601String(), $data['updated_at']);
    }

    /** @test */
    public function testIndexStatusCodeIs200()
    {
        $this->get('/books')->seeStatusCode(200)->seeJson([]);
    }
}